import { defineStore } from 'pinia'

export default function elementStores() {
    return defineStore('elements', {
        state: () => ({
            courses: [
                {
                    module: 'Module 1',
                    time: '4 Weeks',
                    field: 'Digital Literacy',
                    desc: "Embark on a journey of digital literacy with our comprehensive course. Develop a solid understanding of essential computer fundamentals and data processing concepts. Learn to navigate the digital landscape confidently, from mastering basic computer operations to exploring data manipulation techniques. Gain practical skills in utilizing software tools for efficient data processing, analysis, and presentation.",
                    image: '..../assets/others/digitalLiteracy.png',
                },
                {
                    module: 'Module 2',
                    time: '6 Weeks',
                    field: 'Web Development fundamentals',
                    desc: 'Discover the fundamentals of web development in our introductory course. Learn HTML, CSS, and JavaScript essentials to build and style web pages. Acquire foundational skills for creating interactive and responsive websites. Perfect for beginners and those looking to grasp the basics of web development.',
                    image: '..../assets/others/webDevFund.png',
                },
                {
                    module: 'Module 3',
                    time: '6 Months',
                    field: 'Full-stack Development',
                    desc: 'Discover the full range of web development in our Fullstack Web Development Mastery course. Seamlessly blend front-End and backend expertise to become a versatile developer creating holistic web solutions. Excel in Front-End tools for captivating interfaces, while exploring server-side technologies, APIs, databases, and security in depth.',
                    image: '..../assets/others/fullstack.png',
                },
                {
                    module: 'Module 4',
                    time: '3 Weeks',
                    field: 'Web Design with CMS',
                    desc: 'Learn Web Design with CMS: Create stunning websites using Content Management Systems. Master layout design, UI/UX principles, and CMS integration. Build dynamic, responsive sites without coding. Perfect for beginners and designers looking to enhance skills in designing and managing websites efficiently.',
                    image: '..../assets/others/WebDesignWithCms.png',
                },
                {
                    module: 'Module 5',
                    time: '3 Months',
                    field: 'Front-End Development',
                    desc: 'Explore the core aspects of front-End web development in this hands-on course. Learn web design tools to create engaging and responsive user interfaces. Develop the skills to build and style web content, add interactivity, and ensure optimal user experiences across devices. Perfect for beginners and those looking to strengthen their front-End skills.',
                    image: '..../assets/others/front-End.png',
                },
                {
                    module: 'Module 6',
                    time: '3 Months',
                    field: 'Back-End Development',
                    desc: "Dive into the world of backend web development with our comprehensive course. Discover the backend's crucial role in powering web applications, databases, and server-side logic.Gain hands-on experience in building robust and scalable backend systems, making you proficient in delivering efficient and secure web solutions.",
                    image: '..../assets/others/backEnd.png' ,
                },
                {
                    module: 'Module 7',
                    time: '8 Weeks',
                    field: 'MS Office User Professional',
                    desc: 'Elevate your proficiency in Microsoft Office with our Professional User course. Learn advanced features of Word, Excel, PowerPoint. Develop essential skills in data analysis, document formatting, presentation design, and efficient communication. Ideal for enhancing workplace productivity and expanding your Microsoft Office expertise.',
                    image: '..../assets/others/msOfficeUserProfessional.png',
                },
                {
                    module: 'Module 8',
                    time: '2 Months',
                    field: 'UI / UX Designs',
                    desc: 'Master the art of UI/UX and software design in our comprehensive course. Learn design principles, wireframing, prototyping, and user-centered approaches. Gain hands-on experience creating visually stunning and user-friendly digital solutions. Perfect for aspiring designers and developers seeking to craft exceptional user experiences.',
                    image: '..../assets/others/uiUxSoftwareDesigns.png',
                },
                {
                    module: 'Module 9',
                    time: '8 Weeks',
                    field: 'Python Programming',
                    desc: 'Master Python Programming from basics to advanced levels in our comprehensive course. Learn syntax, data structures, algorithms, and object-oriented concepts. Explore web development, data analysis, and more. Build real-world projects and enhance your coding skills. Perfect for beginners and those looking to elevate their Python proficiency.',
                    image: '..../assets/others/pythonProgramming.png',
                },
                {
                    module: 'Module 10',
                    time: '8 Weeks',
                    field: 'Mobile App Development',
                    desc: 'Dive into Mobile App Development with our course. Learn to create responsive, feature-rich apps for iOS and Android. Master essential languages, frameworks, and design principles. Gain hands-on experience building functional and engaging mobile applications. Perfect for aspiring developers and those eager to innovate in the mobile app landscape.',
                    image: '..../assets/others/mobileAppDev.png',
                },
                {
                    module: 'Module 11',
                    time: '8 Weeks',
                    field: 'Java Programming',
                    desc: "Master Java programming essentials in our concise course. Learn syntax, data types, control structures, and object-oriented principles. Develop practical skills in creating applications and understanding Java's versatility. Perfect for beginners and those aiming to strengthen their Java proficiency for software development.",
                    image: '..../assets/others/javaProgramming.png',
                },
                {
                    module: 'Module 12',
                    time: '8 Weeks',
                    field: 'Graphics Designs',
                    desc: 'Elevate your graphic design skills with our intermediate course. Delve into advanced techniques in typography, layout composition, image manipulation, and branding. Develop a diverse portfolio while honing your creative vision. Perfect for designers seeking to take their graphic design expertise to the next level.',
                    image: '..../assets/others/graphicsDesign.png',
                },
                {
                    module: 'Module 13',
                    time: '4 Weeks',
                    field: 'Digital Marketing & Social Media Enginering',
                    desc: 'Elevate your digital marketing prowess with our intermediate course. Dive into advanced strategies, analytics, and social media optimization. Harness the power of data-driven decisions and master effective online campaigns. Perfect for marketers aiming to deepen their skills in the dynamic landscape of digital marketing and social media engineering.',
                    image: '..../assets/others/digitalMarketing.png',
                },
                {
                    module: 'Module 14',
                    time: '12 Weeks(Weekend)',
                    field: 'Data Analysis',
                    desc: 'Elevate your Excel skills in our intermediate-level course. Become a proficient Excel Power User through advanced functions, data manipulation, and visualization techniques. Uncover insights with data analysis tools, PivotTables, and charts. Ideal for individuals aiming to enhance their data handling...',
                    image: '..../assets/others/excelPowerUser.png',
                },
                {
                    module: 'Module 15',
                    time: '4 Weeks',
                    field: 'Windows Server Administration & Management',
                    desc: 'Elevate Windows Server skills through our intermediate course. Master advanced administration, user management, group policies, security, and performance optimization. Ideal for IT professionals aiming to enhance Windows Server expertise and streamline organizational infrastructure for seamless network operations.',
                    image: '..../assets/others/windowsServerAdministration&Management.png',
                },
                {
                    module: 'Module 16',
                    time: '4 Weeks',
                    field: 'Linux Administration',
                    desc: 'Enhance your Linux admin skills with our intermediate course. Delve deeper into system management, networking, security, and scripting. Learn to configure, troubleshoot, and optimize Linux environments effectively. Ideal for those with basic Linux familiarity, aspiring to excel in diverse IT administration roles and responsibilities. Develop expertise for successful careers.',
                    image: '..../assets/others/linuxAdministration.png',
                },
                {
                    module: 'Module 17',
                    time: '8 Weeks(Weekend)',
                    field: 'Red Hat System Admin.',
                    desc: 'Elevate your Red Hat System Administration skills with our comprehensive course. Delve into Linux, networking, security, and automation intricacies. Master complex tasks and enterprise-level configurations. This course is ideal for experienced professionals seeking to proficiently manage and optimize Red Hat systems, ensuring robust performance and security in various IT environments.',
                    image: '..../assets/others/redHatSystemAdmin.png',
                },
                {
                    module: 'Module 18',
                    time: '4 Weeks(Weekend)',
                    field: 'Computer Networking Fundamentals',
                    desc: 'Dive into Computer Networking Fundamentals for beginners. Learn essential concepts of data transmission, network protocols, IP addressing, and network topologies. Acquire practical skills to set up, troubleshoot, and secure basic networks. Ideal for newcomers seeking a solid foundation in connecting and managing digital systems.',
                    image: '..../assets/others/computerNetworkingFundamentals.png',
                },
                {
                    module: 'Module 19',
                    time: '6 Weeks(Weekend)',
                    field: 'Advanced Computer Networking',
                    desc: 'Delve into Advanced Computer Networking in our focused course. Explore cutting-edge protocols, network architecture, security, and scalability. Gain hands-on expertise in designing, optimizing, and managing complex networks. Ideal for IT professionals and network engineers aiming to elevate their skills in the dynamic world of modern connectivity.',
                    image: '..../assets/others/AdvancedComputerEmgineering.png',
                },
                {
                    module: 'Module 20',
                    time: '3 Months (Weekend)',
                    field: 'Cisco Certified Network Associate',
                    desc: 'Elevate your networking expertise with our Advanced Cisco Certified Network Associate course. Dive deep into complex network configurations, protocols, and troubleshooting. Master advanced Cisco technologies, enhancing your ability to design, implement, and manage robust network solutions. Perfect for professionals aiming to excel in intricate networking environments.',
                    image: '..../assets/others/ciscoCertifiedNetworkAssociate.png',
                },
                {
                    module: 'Module 21',
                    time: '10 Weeks(Weekend)',
                    field: 'Cyber Security & Ethical Hacking',
                    desc: 'Dive into Advanced Cyber Security & Ethical Hacking with our intensive course. Explore cutting-edge techniques, threat analysis, and penetration testing. Develop expertise in securing networks, systems, and applications. Ideal for cybersecurity professionals aiming to elevate their skills in safeguarding digital environments and conducting ethical hacking assessments.',
                    image: '..../assets/others/cyberSecurity&EthicalHacking.png',
                },
                {
                    module: 'Module 22',
                    time: '8 Weeks(Weekend)',
                    field: 'Virtualization Technology',
                    desc: 'Dive deep into Advanced Virtualization Technology with our course. Explore cutting-edge techniques in virtualization, containerization, and cloud computing. Develop expertise in optimizing resource utilization, scalability, and infrastructure management. Ideal for tech professionals looking to elevate their virtualization skills and drive efficient IT solutions.',
                    image: '..../assets/others/virtualizationTechnology.png',
                },
                {
                    module: 'Module 23',
                    time: '2 Months(Weekend)',
                    field: 'Accounting and ERP Software',
                    desc: 'Delve into Accounting and ERP Software with our focused course. Acquire a comprehensive understanding of financial management, ledger systems, and enterprise resource planning. Develop practical skills in utilizing industry-leading software for efficient business operations. Ideal for those pursuing a career in finance and business management.',
                    image: '..../assets/others/AccountingAndERPSoftware.png',
                },
                {
                    module: 'Module 24',
                    time: '4 Weeks(Weekend)',
                    field: 'SPSS DATA ANALYSIS',
                    desc: 'Unlock the power of data analysis with our SPSS course. Learn to navigate, manipulate, and derive insights from data using IBM SPSS Statistics. Explore statistical techniques, hypothesis testing, and data visualization. Gain practical skills in data interpretation and decision-making. Ideal for beginners and professionals seeking to harness data for informed choices.',
                    image: '..../assets/others/spss.png',
                },
            ],
            testifier: 0,
            testimonials: [
                {
                    name: 'Fellow Zakariyyah Okeyale ',
                    occupation: 'Front-End Dev.',
                    speech: 'I had an incredible experience at Dervac Hub!  The comprehensive curriculum, hands-on projects and knowledgeable instructors made learning complex concepts a breeze. The practical approach to teaching ensured that I not only understood the theory but could also apply it in real-world scenarios. Am excited about the opportunities ahead. I highly recommend Dervac Hub to anyone looking to kickstart or enhance their career in technology.',
                    image: '../assets/others/alfa-zakariyyah.jpg'
                },
                {
                    name: 'Fellow Hammed Sanni',
                    occupation: 'Front-End Dev.',
                    speech: 'At Dervac, we believe that everyone deserves the opportunity to pursue their dreams without the burden of the debt. Created a program that puts you in control of your education and career sapiente, quia ab commodi veniam. Reiciendis neque dignissimos voluptatem modi est at! Architecto deleniti sa',
                    image: '../assets/testimonial-2.jpg'
                },
                {
                    name: 'Fellow Balkis Taiwo ',
                    occupation: 'Front-End Dev.',
                    speech: 'Reflecting on my time at Dervac Hub, I am grateful for the experience I gained as an IT personnel and web developer intern. The combination of troubleshooting IT issues and crafting innovative web solutions has equipped me with a versatile skill set that I am eager to leverage in my future career endeavors.',
                    image: '../assets/others/balkis.jpg'
                },
                {
                    name: 'Fellow Yusuf Olatunji',
                    occupation: 'Front-End Dev.',
                    speech: "I would like to use this medium to thank DERVAC for their wonderful contribution. I just wanted to share a quick note and let you know that  DERVAC is the best place to learn.   I'm so glad that I am part of the team. I always thought that Web Dev is hard to learn but you prove me wrong. Thanks, Jaza kumu lahu khairan.",
                    image: '../assets/others/agba.jpg'
                },
            ],
            showSummer: false,
            showWeekend: false,
            showRemote: false,
            showWeekday: false,
            showExecutive: false,
            showAnswer: false,
            learnMoreBgBlue: true,
            changeHireColor: false,
            changeApplyNowColor: false,
            drop: false,
            dropCollaborateOptions: false,
            team: [
                { 
                    id: 1,
                    name: 'Muhsin Ishaq Anjorin',
                    based: "CIO / Team Lead", 
                    linkedIn: 'https://www.linkedin.com/in/anjorin4us/',
                    website: 'https://anjorin.net/',
                    twitter: 'https://twitter.com/anjorin4us',
                    imageUrl: 'src/assets/anjorin.JPG'
                },
                { 
                    id: 2,
                    name: 'Ibrahim Opeyemi',
                    based: "Enterprise / IT Support", 
                    linkedIn: 'https://www.linkedin.com/in/ibrahim-akorede-53a53527b/',
                    website: '../assets/ib.jpg',
                    twitter: '#',
                    imageUrl: '../assets/ib.jpg',
                },
                { 
                    id: 3,
                    name: 'AbdulQoyum Aliyu',
                    based: "Software Developer", 
                    linkedIn: 'https://www.linkedin.com/in/abdulqoyum-aliyu-ba6355183/', 
                    website: 'https://www.linkedin.com/in/abdulqoyum-aliyu-ba6355183/', 
                    twitter: 'https://www.linkedin.com/in/abdulqoyum-aliyu-ba6355183/', 
                    imageUrl: '../assets/aliy.png', 
                },
                { 
                    id: 4,
                    name: 'Dehinde Fowora',
                    based: "Systems Infrastructure", 
                    linkedIn: 'https://www.linkedin.com/in/dehinde-nasrudeen-fowora-665072b5/', 
                    website: '../assets/dehinde.jpg', 
                    twitter: '#', 
                    imageUrl: '../assets/dehinde.jpg', 
                },
                { 
                    id: 5,
                    name: 'Sikiru Jimoh',
                    based: "Systems Infrastructure", 
                    linkedIn: '../assets/dehinde.jpg', 
                    website: '../assets/dehinde.jpg', 
                    twitter: '#', 
                    imageUrl: '../assets/dehinde.jpg', 
                },
                { 
                    id: 6,
                    name: 'Lawal-fowora Khadijah',
                    based: "UI/UX Designer", 
                    linkedIn: 'https://www.linkedin.com/in/khadijah-lawal-fowora-b5244160/', 
                    website: '../assets/dehinde.jpg', 
                    twitter: '#', 
                    imageUrl: '../assets/dehinde.jpg', 
                },
                { 
                    id: 7,
                    name: 'Maruf Ajagunna',
                    based: "Software Developer", 
                    linkedIn: 'https://www.linkedin.com/in/marufdeen-ajagunna-a634a4113/', 
                    website: '../assets/ajagunna.jpg', 
                    twitter: 'https://twitter.com/MarufdeenB', 
                    imageUrl: '../assets/ajagunna.jpg', 
                },
                { 
                    id: 8,
                    name: 'Hassan Akeredolu',
                    based: "Technical Officer", 
                    linkedIn: 'https://www.linkedin.com/in/akeredolu-hassan-8a799850/', 
                    website: '../assets/hassan.jpg', 
                    twitter: 'https://twitter.com/HassanAkeredolu', 
                    imageUrl: '../assets/hassan.jpg', 
                },
                { 
                    id: 9,
                    name: 'Sanni Hammed',
                    based: "Front-End Developer", 
                    linkedIn: 'https://www.linkedin.com/in/hammed-sanni-b27765236/',
                    website: 'https://abdulhameedi.github.io/portfolio_june_23/',
                    twitter: 'https://twitter.com/HammedSanni5',
                    imageUrl: '../assets/hammed.png'
                },               
                { 
                    id: 10,
                    name: 'Luqmon AbdurRahman',
                    based: "Front-End Developer", 
                    linkedIn: 'https://www.linkedin.com/in/surecoders/', 
                    website: '../assets/ajagunna.jpg', 
                    twitter: 'https://twitter.com/MarufdeenB', 
                    imageUrl: '../assets/tijani.jpg', 
                },
                { 

                    id: 11,
                    name: 'Fawwaz Makinde',
                    based: "Front-End Developer", 
                    linkedIn: '../assets/fawaz.jpg', 
                    website: '../assets/fawaz.jpg', 
                    twitter: '../assets/fawaz.jpg', 
                    imageUrl: '../assets/fawaz.jpg', 
                },
                { 
                    id: 12,
                    name: 'Yunus Qudus',
                    based: "Software Engineer", 
                    linkedIn: 'https://www.linkedin.com/in/abdulqudus-yunus-2a1153151/', 
                    website: '#', 
                    twitter: '#', 
                    imageUrl: '../assets/yunusSanni.jpg', 
                },
                { 
                    id: 13,
                    name: 'Lateef Kazeem',
                    based: "IT associate", 
                    linkedIn: '#', 
                    website: '#', 
                    twitter: '#', 
                    imageUrl: '../assets/yunusSanni.jpg', 
                },
            ],
            fellows: [
                    { 
                        id: 1,
                        name: 'Olatunji Yusuf',
                        based: "Front-End Developer", 
                        website: '../assets/agba.jpg', 
                        linkedIn: '../assets/agba.jpg', 
                        twitter: '../assets/agba.jpg', 
                        imageUrl: '../assets/agba.jpg',
                        year: 2023,
                    },
                    { 
                        id: 1,
                        name: 'Abdulrahman Luqman',
                        based: "Front-End Developer", 
                        website: '../assets/luqman.png', 
                        linkedIn: '../assets/luqman.png', 
                        twitter: 'https://twitter.com/luqmanola60', 
                        imageUrl: '../assets/luqman.png', 
                        year: 2023,
                    },
                    { 
                        id: 3,
                        name: 'Olawore Emmanuel',
                        based: "Front-End Developer", 
                        website: '../assets/emma.jpg', 
                        linkedIn: '../assets/emma.jpg', 
                        twitter: '../assets/emma.jpg', 
                        imageUrl: '../assets/emma.jpg', 
                        year: 2023,
                    },
                    { 
                        id: 4,
                        name: 'Balkis Taiwo',
                        based: "Front-End Developer", 
                        website: '../assets/balkis.jpg', 
                        linkedIn: '../assets/balkis.jpg', 
                        twitter: '../assets/balkis.jpg', 
                        imageUrl: '../assets/balkis.jpg', 
                        year: 2023,
                    },
                    { 
                        id: 5,
                        name: 'Adam Ayinde',
                        based: "Front-End Developer", 
                        website: '../assets/adam.jpg', 
                        linkedIn: '../assets/adam.jpg', 
                        twitter: '../assets/adam.jpg', 
                        imageUrl: '../assets/adam.jpg', 
                        year: 2022,
                    },
                    { 
                        id: 7,
                        name: 'Okeyale Zakariya',
                        based: "Front-End Developer", 
                        website: '../assets/zakariyya.jpg', 
                        linkedIn: '../assets/zakariyya.jpg', 
                        twitter: 'https://twitter.com/OkeyaleZ', 
                        imageUrl: '../assets/zakariyya.jpg', 
                        year: 2023,
                    },
                    { 
                        id: 8,
                        name: 'Abdulazeez Abdulganiy',
                        based: "Front-End Developer", 
                        website: '../assets/abdulaziz.jpg', 
                        linkedIn: '../assets/abdulaziz.jpg', 
                        twitter: '../assets/abdulaziz.jpg', 
                        imageUrl: '../assets/abdulaziz.jpg', 
                        year: 2023,
                    },
                    { 
                        id: 9,
                        name: 'Abdullah Abdulkareem',
                        based: "Front-End Developer", 
                        website: '../assets/emma.jpg', 
                        linkedIn: '../assets/emma.jpg', 
                        twitter: '../assets/emma.jpg', 
                        imageUrl: '../assets/emma.jpg', 
                        year: 2023,
                    },
                    { 
                        id: 10,
                        name: 'Olakunmi Abdulsalam',
                        based: "Front-End Developer", 
                        website: '../assets/olakunmi.jpg', 
                        linkedIn: '../assets/olakunmi.jpg', 
                        twitter: '../assets/olakunmi.jpg', 
                        imageUrl: '../assets/olakunmi.jpg', 
                        year: 2022,
                    },
                    { 
                        id: 11,
                        name: 'Sanni Hammed',
                        based: "Front-End Developer", 
                        linkeyouyoudIn: 'https://www.linkedin.com/in/hammed-sanni-b27765236/',
                        website: 'https://abdulhameedi.github.io/portfolio_june_23/',
                        twitter: 'https://twitter.com/HammedSanni5',
                        imageUrl: '../assets/hammed.png',
                        year: 2022,
                    },
                    { 
                        id: 12,
                        name: 'Esther Odutayo',
                        based: "Front-End Developer", 
                        linkedIn: 'https://www.linkedin.com/in/esther-odutayo-06a116274/', 
                        website: '../assets/esther.jpg', 
                        twitter: '../assets/esther.jpg', 
                        imageUrl: '../assets/esther.jpg', 
                        year: 2023,
                    },
                    { 
                        id: 13,
                        name: 'Fawwaz Makinde',
                        based: "Front-End Developer", 
                        linkedIn: '../assets/fawaz.jpg', 
                        website: '../assets/fawaz.jpg', 
                        twitter: '../assets/fawaz.jpg', 
                        imageUrl: '../assets/fawaz.jpg',
                        year: 2023, 
                    },
                    { 
                        id: 13,
                        name: 'Abdul-Roheem Aromire',
                        based: "Front-End Developer", 
                        linkedIn: '../assets/fawaz.jpg', 
                        website: '../assets/fawaz.jpg', 
                        twitter: '../assets/fawaz.jpg', 
                        imageUrl: '../assets/fawaz.jpg',
                        year: 2021, 
                    },
                    { 
                        id: 13,
                        name: 'Usman Zahradeen',
                        based: "Front-End Developer", 
                        linkedIn: '../assets/fawaz.jpg', 
                        website: '../assets/fawaz.jpg', 
                        twitter: '../assets/fawaz.jpg', 
                        imageUrl: '../assets/fawaz.jpg',
                        year: 2021, 
                    },
                    { 
                        id: 13,
                        name: 'Aransiola Abdulquadri',
                        based: "Front-End Developer", 
                        linkedIn: '../assets/fawaz.jpg', 
                        website: '../assets/fawaz.jpg', 
                        twitter: '../assets/fawaz.jpg', 
                        imageUrl: '../assets/fawaz.jpg',
                        year: 2021, 
                    },
                    { 
                        id: 13,
                        name: 'Kosoko Quam',
                        based: "Front-End Developer", 
                        linkedIn: '../assets/fawaz.jpg', 
                        website: '../assets/fawaz.jpg', 
                        twitter: '../assets/fawaz.jpg', 
                        imageUrl: '../assets/fawaz.jpg',
                        year: 2021, 
                    },
                    { 
                        id: 13,
                        name: 'AbdulRasheed Sirajudeen',
                        based: "Front-End Developer", 
                        linkedIn: '../assets/fawaz.jpg', 
                        website: '../assets/fawaz.jpg', 
                        twitter: '../assets/fawaz.jpg', 
                        imageUrl: '../assets/fawaz.jpg',
                        year: 2022, 
                    },
                
            ],
            showAnswerInMainPage: false,
            onPage: true,
            nextPage: true,
            nextAfterPage: true,
            Apply: 1,
            ApplyPageShow: true,
            disableScroll: false,
            showButton: false,
            testimonialsPage: [
                {
                    name: 'Okeyale Zakariyyah',
                    occupation: 'Front-End Dev.',
                    testimony: 'I had an incredible experience at Dervac Hub!  The comprehensive curriculum, hands-on projects and knowledgeable instructors made learning complex concepts a breeze. The practical approach to teaching ensured that I not only understood the theory but could also apply it in real-world scenarios. Am excited about the opportunities ahead. I highly recommend Dervac Hub to anyone looking to kickstart or enhance their career in technology.',
                    image: '../assets/others/alfa-zakariyyah.jpg'
                },
                {
                    name: 'Sanni AbdHameed',
                    occupation: 'Front-End Dev.',
                    testimony: "DervacHub has been a beacon of guidance in my journey toward becoming a proficient developer. The curriculum, thoughtfully curated with industry demands in mind, allowed me to grasp intricate concepts effortlessly. What truly stood out was their emphasis on practical application – from coding challenges to collaborative projects – fostering skills that translate directly into the real world. DervacHub's dedication to my growth and success has not only shaped my technical abilities but also instilled in me a profound confidence to innovate and create. I am immensely grateful for the enriching experience and wholeheartedly recommend DervacHub to aspiring developers.",
                    image: '../assets/testimonial-2.jpg'
                },
                {
                    name: 'AbdurRasheed',
                    occupation: 'Front-End Dev.',
                    testimony: 'Dervac Global Services;it was a great experience having my SIWES with you, you are the real definition of industrial training as I had the opportunity to get practical experience of what Computet Science entails, I got my bearing as student of computer science at Dervac and also was able to know my potentials as Dervac gave me the opportunity to explore alot of fields in IT.One of the greatest potential of Dervac is  "follow-up",she made herself always available to support my growth.Thanks so much Dervac',
                    image: '../assets/others/abdrrasheed.jpg'
                },
                {
                    name: 'Taiwo Balkis',
                    occupation: 'Front-End Dev.',
                    testimony: 'During my stay at Dervac Hub as a software developer and an IT personnel, I had the privilege of being part of an innovative and forward-thinking team. The office buzzed with creativity and collaboration, making each day an exciting journey. I learned to seamlessly integrate aesthetics with functionality, resulting in user-friendly. Regular stand-up meetings ensured that everyone was aligned, and I appreciated the camaraderie and support within the team. Code reviews were a valuable opportunity for learning and growth, and I eagerly learned from my peers.  ',
                    image: '../assets/others/Balkis.jpg',
                },
                {
                    name: 'Aadam',
                    occupation: 'Front-End Dev.',
                    testimony: "Dear DERVAC, I'd like to express my gratitude for your supervision and guidance during my internship. My experience was very valuable, and I've gained so much insight into the world of ICT. I enjoyed working and collaborating with you, my fellow interns back then and now. I was delighted to be part of such an amazing and organized INFORMATION TECHNOLOGY organization.Thanks again for this incredible internship, and I wish you and the [DERVAC TEAM] all the best.",
                    image: '../assets/others/Oogee.jpg',
                },
                {
                    name: 'AbdSalaam',
                    occupation: 'Front-End Dev.',
                    testimony: 'My internship at Dervac hub was truly an invaluable and transformative experience. Throughout my time there, I had the privilege of gaining valuable insights and skills in various areas, including team management, which taught me how to effectively collaborate and lead in a professional setting. Additionally, the exposure to different challenging projects allowed me to refine my problem-solving abilities and think creatively to overcome obstacles. One of the standout aspects of my internship was the emphasis on computer literacy.',
                    image: '../assets/others/abdSalam.jpg',
                },
                {
                    name: 'Okeyale Zakariyyah',
                    occupation: 'Front-End Dev.',
                    testimony: 'I had an incredible experience at Dervac Hub!  The comprehensive curriculum, hands-on projects and knowledgeable instructors made learning complex concepts a breeze. The practical approach to teaching ensured that I not only understood the theory but could also apply it in real-world scenarios. The engaging learning environment created a positive atmosphere that fostered growth and confidence. Thanks to this training. Am excited about the opportunities ahead. I highly recommend Dervac Hub to anyone looking to kickstart or enhance their career in technology',
                    image: '../assets/others/alfa-Zakariyyah',
                },
                {
                    name: 'Yusuf Olatunji',
                    occupation: 'Front-End Dev.',
                    testimony: "I would like to use this medium to thank DERVAC for their wonderful contribution. I just wanted to share a quick note and let you know that  DERVAC is the best place to learn.   I'm so glad that I am part of the team. I always thought that Web Dev is hard to learn but you prove me wrong.Thanks, Jaza kumu lahu khairan.",
                    image: '../assets/others/agba.jpg',
                },
                {
                    name: "AbdGaniy AbdA'zeez",
                    occupation: 'Front-End Dev.',
                    testimony: "I am taking this opportunity to express my heartfelt gratitude to DervacHub. They have taken me from being a computer fundamentalist to a skilled front-End developer in just six months. While it demanded dedicated hard work and relentless effort, the results have been truly rewarding. The transformation and growth I've experienced are a testament to the value and commitment that DervacHub brings to its programs." ,
                    image: '../assets/abdulaziz.jpg',
                },
                {
                    name: 'Luqman AbdurRahman',
                    occupation: 'Front-End Dev.',
                    testimony: "Joining DervacHub was a pivotal moment in my career journey. The guidance and mentorship I received there were instrumental in shaping me into a competent and confident developer. The hands-on approach to learning, coupled with real-world projects, enabled me to apply theoretical concepts to practical situations.Thanks to DervacHub, I now possess the skills and knowledge needed to thrive in the ever-evolving tech industry.",
                    image: '../assets/luqman.png'
                },
                {
                    name: 'Makinde Fawwaz',
                    occupation: 'Front-End Dev.',
                    testimony: 'My experience with DervacHub has been nothing short of phenomenal. Enrolling in their program was a game-changer for me. The curriculum is expertly designed, covering a wide spectrum of topics crucial for a well-rounded developer. From coding fundamentals to advanced techniques, I was amazed at how seamlessly they guided me through the learning journey.        one of the qualities that truly sets DervacHub apart is their incredible support system. The our tutor is not only knowledgeable but also incredibly approachable. Whenever I hit a roadblock or needed clarification, he is right there to guide me, making the learning process smoother and more enjoyable.',
                    image: '../assets/fawaz.jpg',
                },
                {
                    name: 'Esther',
                    occupation: 'Front-End Dev.',
                    testimony: " DervacHub doesn't just teach you to code; they empower you to think critically and solve complex challenges. I am immensely grateful for the transformative experience and highly recommend DervacHub to anyone aspiring to excel in the world of technology. They exceeded all my expectations in my pursuit of becoming a proficient developer. The structured curriculum, coupled with their emphasis on hands-on learning, accelerated my growth exponentially. ",
                    image: '../assets/esther.jpg',
                },
                {
                    name: 'Olawore Emmanuel',
                    occupation: 'Front-End Dev.',
                    testimony: "Enrolling in DervacHub was a decision I'll forever cherish. Their comprehensive program transformed my passion for technology into tangible skills. The practical projects and real-world simulations equipped me to navigate the dynamic landscape of development. I'm immensely grateful for the opportunity and confident in recommending DervacHub to anyone seeking a transformative learning experience.",
                    image: '../assets/emma.jpg'
                }
            ]
        })
    })()
}
